export const ALL_AVAILABLE_SKILLS = [
  'Python',
  'JavaScript',
  'React.js',
  'Node.js',
  'HTML',
  'CSS',
  'SQL',
  'NoSQL',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'Go',
  'PHP',
  'TypeScript',
  'Django',
  'Flask',
  'Express.js',
  'Spring Boot',
  'ASP.NET',
  'Vue.js',
  'Angular',
  'Redux',
  'MobX',
  'SASS',
  'Less',
  'Bootstrap',
  'Tailwind CSS',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'CI/CD',
  'Git',
  'REST API',
  'GraphQL',
  'Unit Testing',
  'Integration Testing',
  'Agile Methodologies',
  'Scrum',
  'Kanban',
  'Project Management',
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'Computer Vision',
  'Natural Language Processing',
  'TensorFlow',
  'PyTorch',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Excel',
  'Tableau',
  'Power BI',
  'UI Design',
  'UX Design',
  'Figma',
  'Sketch',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  'Blender',
  '3D Modeling',
  'Animation',
  'Video Editing',
  'Content Creation',
  'SEO',
  'SEM',
  'Digital Marketing',
  'Social Media Marketing',
  'Copywriting',
  'Blogging',
  'Public Speaking',
  'Negotiation',
  'Problem Solving',
  'Critical Thinking',
  'Leadership',
  'Teamwork',
  'Communication',
  'Time Management',
  'Financial Modeling',
  'Business Analysis',
  'Market Research',
  'Sales',
  'Customer Service',
  'Cybersecurity',
  'Networking',
  'System Administration',
  'Cloud Security',
  // Add many more skills as needed
];
