export const ALL_AVAILABLE_SKILLS = [
  // Programming Languages
  'Bash',
  'C',
  'C#',
  'C++',
  'Dart',
  'Elixir',
  'Go',
  'Haskell',
  'Java',
  'JavaScript',
  'Kotlin',
  'MATLAB',
  'Objective-C',
  'PHP',
  'PowerShell',
  'Python',
  'R',
  'Ruby',
  'Rust',
  'Scala',
  'Swift',
  'TypeScript',

  // Web Fundamentals
  'HTML',
  'CSS',
  'SASS',
  'Less',
  'Responsive Design',
  'Accessibility (a11y)',

  // Frontend Frameworks & Tooling
  'React.js',
  'Next.js',
  'Redux',
  'Redux Toolkit',
  'Redux Saga',
  'Zustand',
  'Vue.js',
  'Nuxt.js',
  'Angular',
  'Svelte',
  'SvelteKit',
  'Tailwind CSS',
  'Bootstrap',
  'Material UI',
  'Ant Design',
  'Chakra UI',
  'Styled Components',
  'CSS Modules',
  'Three.js',
  'WebGL',
  'Canvas API',
  'Webpack',
  'Vite',
  'Rollup',
  'Babel',
  'Storybook',

  // Backend Frameworks
  'Node.js',
  'Express.js',
  'NestJS',
  'Fastify',
  'Koa',
  'Hapi',
  'Django',
  'Flask',
  'FastAPI',
  'Spring',
  'Spring Boot',
  'ASP.NET',
  '.NET Core',
  'Ruby on Rails',
  'Laravel',
  'Symfony',
  'Phoenix (Elixir)',
  'Gin (Go)',
  'Fiber (Go)',

  // Mobile & Cross-Platform
  'React Native',
  'Flutter',
  'Android',
  'iOS',
  'SwiftUI',
  'Jetpack Compose',

  // Databases & Storage
  'SQL',
  'NoSQL',
  'MySQL',
  'PostgreSQL',
  'SQLite',
  'MariaDB',
  'SQL Server',
  'MongoDB',
  'DynamoDB',
  'Redis',
  'Memcached',
  'Cassandra',
  'Neo4j',
  'Elasticsearch',
  'Solr',
  'Firebase Realtime Database',
  'Firestore',
  'Supabase',
  'FaunaDB',
  'Snowflake',
  'BigQuery',
  'Redshift',
  'ClickHouse',

  // Messaging & Streaming
  'Apache Kafka',
  'RabbitMQ',
  'NATS',
  'ActiveMQ',
  'Amazon SQS',
  'Amazon SNS',

  // Data Engineering & Processing
  'ETL',
  'ELT',
  'Apache Airflow',
  'Apache Spark',
  'Hadoop',
  'Hive',
  'Trino (Presto)',
  'Flink',
  'Dask',
  'Apache Beam',
  'dbt',

  // Cloud & DevOps
  'AWS',
  'Azure',
  'Google Cloud Platform',
  'Docker',
  'Kubernetes',
  'Helm',
  'Terraform',
  'Pulumi',
  'Ansible',
  'Chef',
  'Puppet',
  'CI/CD',
  'Git',
  'GitHub Actions',
  'GitLab CI',
  'Jenkins',
  'CircleCI',
  'Travis CI',
  'Argo CD',
  'Prometheus',
  'Grafana',
  'ELK Stack',
  'OpenTelemetry',
  'Sentry',
  'Datadog',
  'New Relic',

  // APIs & Protocols
  'REST API',
  'GraphQL',
  'gRPC',
  'tRPC',
  'WebSockets',
  'WebRTC',
  'OAuth 2.0',
  'OpenID Connect',
  'JWT',
  'SAML',

  // Security
  'Auth0',
  'Keycloak',
  'OWASP Top 10',
  'Penetration Testing',
  'Application Security',
  'Cloud Security',
  'Identity and Access Management',

  // Data Science & ML
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'Computer Vision',
  'Natural Language Processing',
  'Reinforcement Learning',
  'MLOps',
  'MLflow',
  'Kubeflow',
  'Weights & Biases',
  'Pandas',
  'NumPy',
  'SciPy',
  'Scikit-learn',
  'TensorFlow',
  'Keras',
  'PyTorch',
  'XGBoost',
  'LightGBM',
  'CatBoost',
  'Hugging Face Transformers',
  'LangChain',
  'OpenAI API',
  'Matplotlib',
  'Seaborn',
  'Plotly',
  'Jupyter Notebook',

  // Analytics & BI
  'Excel',
  'Tableau',
  'Power BI',
  'Looker',
  'Apache Superset',

  // Testing & Quality
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',
  'TDD',
  'BDD',
  'Jest',
  'Mocha',
  'Chai',
  'Vitest',
  'Cypress',
  'Playwright',
  'Testing Library',
  'Postman',
  'Newman',

  // Design & Creative
  'UI Design',
  'UX Design',
  'Design Systems',
  'Figma',
  'Sketch',
  'Adobe XD',
  'Photoshop',
  'Illustrator',
  'After Effects',
  'Premiere Pro',
  'Blender',
  '3D Modeling',
  'Animation',
  'Video Editing',

  // Product & Collaboration
  'Agile Methodologies',
  'Scrum',
  'Kanban',
  'Project Management',
  'Jira',
  'Confluence',
  'Asana',
  'Trello',
  'Notion',

  // Marketing & Content
  'Content Creation',
  'SEO',
  'SEM',
  'Digital Marketing',
  'Social Media Marketing',
  'Copywriting',
  'Blogging',

  // Web3 & Blockchain
  'Blockchain',
  'Solidity',
  'Smart Contracts',
  'Web3.js',
  'Ethers.js',
  'Hardhat',
  'Truffle',

  // Soft Skills
  'Public Speaking',
  'Negotiation',
  'Problem Solving',
  'Critical Thinking',
  'Leadership',
  'Teamwork',
  'Communication',
  'Time Management',

  // Business & Operations
  'Financial Modeling',
  'Business Analysis',
  'Market Research',
  'Sales',
  'Customer Service',
  'Networking',
  'System Administration',

  // Graphic Design & Visual Arts
  'Graphic Design',
  'Visual Identity',
  'Brand Strategy',
  'Art Direction',
  'Creative Direction',
  'Typography',
  'Color Theory',
  'Grid Systems',
  'Layout Design',
  'Print Design',
  'Packaging Design',
  'Editorial Design',
  'Book Design',
  'Poster Design',
  'Infographic Design',
  'Logo Design',
  'Illustration',
  'Concept Art',
  'Storyboarding',
  'Character Design',
  'Environment Design',

  // Photography & Film
  'Photography',
  'Photo Editing',
  'Lightroom',
  'Cinematography',
  'Directing',
  'Screenwriting',
  'Color Grading',
  'DaVinci Resolve',
  'VFX',
  'Compositing',
  'Nuke',
  'Fusion',
  'Motion Graphics',
  '2D Animation',
  '3D Animation',
  'Rigging',
  'Motion Capture',

  // 3D & Game Art
  'Autodesk Maya',
  '3ds Max',
  'ZBrush',
  'Substance Painter',
  'Substance Designer',
  'Houdini',
  'Cinema 4D',
  'Unity',
  'Unreal Engine',
  'Level Design',
  'Game Design',

  // Publishing & Marketing Design
  'Adobe InDesign',
  'Brand Guidelines',
  'Campaign Design',

  // Music & Audio
  'Music Production',
  'Sound Design',
  'Audio Engineering',
  'Mixing',
  'Mastering',
  'Ableton Live',
  'FL Studio',
  'Logic Pro',
  'Pro Tools',

  // Architecture & CAD
  'AutoCAD',
  'Revit',
  'SketchUp',
  'Rhino 3D',
  'BIM',
  'Urban Planning',
  'Architectural Visualization',

  // Life Sciences (Biology & Related)
  'Biology',
  'Molecular Biology',
  'Cell Biology',
  'Microbiology',
  'Immunology',
  'Genetics',
  'Genomics',
  'Proteomics',
  'Biochemistry',
  'Neuroscience',
  'Pharmacology',
  'Toxicology',
  'Epidemiology',
  'Biostatistics',
  'Bioinformatics',
  'Computational Biology',
  'CRISPR',
  'Gene Editing',
  'Cell Culture',
  'PCR',
  'qPCR',
  'Western Blot',
  'ELISA',
  'Flow Cytometry',
  'Microscopy',
  'Confocal Microscopy',
  'Immunohistochemistry',
  'Next-Generation Sequencing (NGS)',
  'Sanger Sequencing',
  'Clinical Research',
  'Medical Imaging',

  // Chemistry & Lab Techniques
  'Organic Chemistry',
  'Inorganic Chemistry',
  'Analytical Chemistry',
  'Physical Chemistry',
  'Mass Spectrometry',
  'Chromatography',
  'HPLC',
  'GC-MS',
  'NMR Spectroscopy',
  'IR Spectroscopy',
  'UV-Vis Spectroscopy',

  // Earth & Environmental Sciences
  'Ecology',
  'Environmental Science',
  'Conservation Biology',
  'Geology',
  'Hydrology',
  'Climatology',
  'Sustainability',
  'GIS',
  'Remote Sensing',
  'ArcGIS',
  'QGIS',
  'Cartography',

  // Mathematics & Statistics
  'Algebra',
  'Calculus',
  'Linear Algebra',
  'Probability',
  'Statistics',
  'Time Series Analysis',

  // Education & Languages
  'Teaching',
  'Curriculum Design',
  'Instructional Design',
  'Academic Writing',
  'Editing',
  'Translation',
];
